# Generated by Django 4.1.13 on 2024-03-07 21:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.TextField()),
                ('index', models.IntegerField()),
                ('url', models.TextField()),
                ('name', models.TextField()),
                ('sku', models.TextField()),
                ('selling_price', models.IntegerField()),
                ('currency', models.TextField()),
                ('availability', models.BooleanField()),
                ('color', models.TextField()),
                ('category', models.TextField()),
                ('source', models.TextField()),
                ('source_website', models.TextField()),
                ('breadcrumbs', models.TextField()),
                ('description', models.TextField()),
                ('brand', models.TextField()),
                ('images', models.TextField()),
                ('country', models.TextField()),
                ('language', models.TextField()),
                ('average_rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('crawled_at', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('rating', models.IntegerField(help_text='Рейтинг от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ecomerce.product')),
            ],
        ),
    ]
